### ISSUE TITLE
Known websites with problems

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Blocker-database#12]
Needs to be reviewed:

* eBay
* PayPal
* Origin
* EA
* Bethesda
* Washinton Post
* NewYork Times
* Digitimes
* Twitch
* XDA Forums
* ....

Edit:
The problems are related to integrated / subscribed filter list in uBlock. 

Edit2:
There also some random 'troll' ads which generating gibberish 'domain'-names (see picture below).

![untitled](https://user-images.githubusercontent.com/727123/32408359-c87c8fda-c196-11e7-9970-fadae7534075.png)

If someone found a solution to the random xxx.biz domains, let me know seems a real problem.

**Comment by The-Commissioner** [comment]
@CHEF-KOCH can you tell me your setup? Are you using all the tools mentioned in this repo? Bcuz it could be anyone of those addons, so will need to check them all for compatibility.
Or is it only uBo or uMaatrix or uBO with uMatrix or anything else?

**Comment by CHEF-KOCH** [comment]
You not need to mention me specifically on my own projects or tickets, cause I read everyone anyway. 

Yeah, you're right the context is missing. The problem is with uBlock, for some reason a lot of rules are _fucked up_. I can't blame anyone for this, moreover it's a general problem with such pages, they getting updated regularly. 

I not touch them often but I will try to stay in sync with them. The thread here is more designed to inform people that there exist problems with such pages and this needs to be fixed within the subscribed filter lists.

**Comment by The-Commissioner** [comment]
> There also some random 'troll' ads which generating gibberish 'domain'-names
If someone found a solution to the random xxx.biz domains, let me know seems a real problem.

For this please try this rule:-
`http*://www.*.bid/*.js^$script,third-party`

**Comment by CHEF-KOCH** [comment]
Won't work for me, I tried on www.skidrowreloaded.com, each time you get a new ID (which means you get new random .bid domains) you see that uBlock 'forgets' them. I gonna think it might be a bug in uBlocks regex system.

**Comment by The-Commissioner** [comment]
That's strange it works for me not only on the site you mentioned but on other sites as well with the same random .bid domains.
I'm using the latest version of uBo and my cache, history was cleared.
I don't think it's uBO problem because if it's working here, that means it's good, maybe some of your other addon is interferring with it's working.
Disable all other addons(just for testing), paste the rule, clear history and restart browser and navigate to site in question.

**Comment by The-Commissioner** [comment]
I think that you need to start over with your rules and configuration as a whole.
I say this because there is overlapping between uBo and uMatrix and within uBo in terms of rules.
E.g.
https://github.com/CHEF-KOCH/NoScript-Whitelist/blob/1c8c3eba2af111a239c836ea8458dd7b9dbc2b02/uBlock%E2%82%80/my-ublock-static-filters.txt#L70

https://github.com/CHEF-KOCH/NoScript-Whitelist/blob/1c8c3eba2af111a239c836ea8458dd7b9dbc2b02/uBlock%E2%82%80/my-ublock-static-filters.txt#L1291

https://github.com/CHEF-KOCH/NoScript-Whitelist/blob/1c8c3eba2af111a239c836ea8458dd7b9dbc2b02/uBlock%E2%82%80/my-ublock-static-filters.txt#L859

The second rule is already covered in the first rule. And the third rule(exclusion one) won't work because of the important modifier in the first rule. So, in this case only 1 rule is working , rest all are rendered useless when filtering.

**Comment by CHEF-KOCH** [comment]
The second rule is specific limited to `/analytics.js$script` while the first one affects everything. The third rule is to avoid problems with Peter Lowe's list. These rules are however correct and will not be touched to avoid troubles with other lists we use.

**Comment by The-Commissioner** [comment]
From what I know I made the right observations [here](https://github.com/CHEF-KOCH/NoScript-Whitelist/issues/12#issuecomment-344795083).
It can be tested by exclusively using these rules on a site with no filter lists enabled(for testing purposes)

**Comment by The-Commissioner** [comment]
Hey this is gaining popularity,check it out: https://github.com/NanoAdblocker/NanoCore
